import { getDictionary } from "@/lib/i18n";
import { LanguageProvider } from "@/components/LanguageProvider";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import ContactUs from "@/src/components/ContactUs";
import "./globals.css";
import ClientCustomCursor from "@/src/components/ClientCustomCursor";

export async function generateStaticParams() {
  return [{ locale: "en" }, { locale: "fr" }, { locale: "es" }];
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props) {
  const { children } = props;

  // ✅ Await props.params before accessing locale
  const { locale } = await props.params;

  const dictionary = await getDictionary(locale);

  return (
    <html lang={locale}>
      <body className="w-screen">
        <LanguageProvider dictionary={dictionary}>
          <NavBar />
          <ClientCustomCursor/>
          <main>{children}</main>
          <ContactUs />
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
